DROP TABLE users IF EXISTS cascade;
DROP TABLE friends IF EXISTS cascade;
DROP TABLE films IF EXISTS cascade;
DROP TABLE rating IF EXISTS cascade;
DROP TABLE likes IF EXISTS cascade;
DROP TABLE film_genre IF EXISTS cascade;
DROP TABLE genre IF EXISTS cascade;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(64) NOT NULL,
    login VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER,
    friend_id INTEGER,
    status BOOLEAN,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (friend_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS rating (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration INTEGER,
    rating_id INTEGER,
    rate INTEGER,
    FOREIGN KEY (rating_id) REFERENCES rating(id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id INTEGER,
    user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (film_id) REFERENCES films(id)
);

CREATE TABLE IF NOT EXISTS genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id INTEGER,
    genre_id INTEGER,
    FOREIGN KEY (film_id) REFERENCES films(id),
    FOREIGN KEY (genre_id) REFERENCES genre(id)
);

INSERT INTO rating (id, rating_name) VALUES (1, 'G');
INSERT INTO rating (id, rating_name) VALUES (2, 'PG');
INSERT INTO rating (id, rating_name) VALUES (3, 'PG-13');
INSERT INTO rating (id, rating_name) VALUES (4, 'R');
INSERT INTO rating (id, rating_name) VALUES (5, 'NC-17');

INSERT INTO genre (id, genre_name) VALUES (1, 'Комедия');
INSERT INTO genre (id, genre_name) VALUES (2, 'Драма');
INSERT INTO genre (id, genre_name) VALUES (3, 'Мультфильм');
INSERT INTO genre (id, genre_name) VALUES (4, 'Триллер');
INSERT INTO genre (id, genre_name) VALUES (5, 'Документальный');
INSERT INTO genre (id, genre_name) VALUES (6, 'Боевик');


